# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicsApp', '0003_ngramduplicates'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='PhrasedText_2',
            field=models.TextField(blank=True),
        ),
    ]
