# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicsApp', '0004_articles_phrasedtext_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='SampledText',
            field=models.TextField(blank=True),
        ),
    ]
