# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicsApp', '0006_articles_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='Type',
            field=models.TextField(blank=True),
        ),
    ]
