# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicsApp', '0007_articles_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoveNgram',
            fields=[
                ('RemoveNgramId', models.AutoField(primary_key=True, serialize=False)),
                ('RemoveGram', models.CharField(max_length=100)),
            ],
        ),
    ]
