# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politicsApp', '0008_removengram'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RemoveNgram',
        ),
    ]
