# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicsApp', '0009_delete_removengram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlengram',
            old_name='StdFrequency',
            new_name='IDF',
        ),
        migrations.RenameField(
            model_name='articlengram',
            old_name='Frequency',
            new_name='TF',
        ),
        migrations.AddField(
            model_name='articlengram',
            name='TFIDF',
            field=models.FloatField(default=0),
        ),
    ]
