# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politicsApp', '0011_auto_20171126_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngram',
            name='IDF',
        ),
    ]
