# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicsApp', '0012_remove_ngram_idf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlengram',
            name='TF',
            field=models.FloatField(default=0),
        ),
    ]
