# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicsApp', '0013_auto_20171126_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngram',
            name='IDF',
            field=models.FloatField(default=0),
        ),
    ]
